import type { Assessment, ClinicalSnapshot, Patient } from "@/features/clinical/types";
import type { DN4Responses } from "@/features/assessments/dn4";
import { DN4_VERSION } from "@/features/assessments/dn4";

/**
 * Deterministic demo dataset used to seed local persistence on first run.
 * Replaced entirely once a real backend is connected.
 */

function patient(p: Omit<Patient, "createdAt" | "updatedAt"> & { createdAt: string }): Patient {
  return { ...p, updatedAt: p.createdAt };
}

export const seedPatients: Patient[] = [
  patient({
    id: "p-1024",
    mrn: "MRN-100482",
    firstName: "Amina",
    lastName: "Haddad",
    dob: "1962-04-11",
    sex: "F",
    phone: "+212 6 12 34 56 78",
    status: "active",
    primaryDiagnosis: "Diabetic peripheral neuropathy",
    comorbidities: ["Type 2 Diabetes", "Hypertension"],
    allergies: "NKDA",
    pharmacist: "Dr. L. Benali",
    department: "Endocrinology",
    visitType: "Outpatient",
    nextFollowUp: "2026-08-05",
    createdAt: "2026-05-14T09:10:00.000Z",
    medications: [
      {
        id: "m-1024-1",
        name: "Pregabalin",
        dose: "75 mg",
        frequency: "BID",
        route: "PO",
        indication: "Neuropathic pain",
        startedOn: "2026-05-14",
      },
      {
        id: "m-1024-2",
        name: "Metformin",
        dose: "1000 mg",
        frequency: "BID",
        route: "PO",
        indication: "T2DM",
        startedOn: "2022-01-03",
      },
      {
        id: "m-1024-3",
        name: "Amlodipine",
        dose: "5 mg",
        frequency: "OD",
        route: "PO",
        indication: "HTN",
        startedOn: "2023-09-10",
      },
    ],
  }),
  patient({
    id: "p-1025",
    mrn: "MRN-100487",
    firstName: "Youssef",
    lastName: "El Amrani",
    dob: "1974-09-30",
    sex: "M",
    phone: "+212 6 55 22 11 09",
    status: "review",
    primaryDiagnosis: "Post-herpetic neuralgia",
    comorbidities: ["Hyperlipidemia"],
    allergies: "Penicillin",
    pharmacist: "Dr. S. Cherkaoui",
    department: "Neurology",
    visitType: "Outpatient",
    nextFollowUp: "2026-08-08",
    createdAt: "2026-06-01T08:00:00.000Z",
    medications: [
      {
        id: "m-1025-1",
        name: "Gabapentin",
        dose: "300 mg",
        frequency: "TID",
        route: "PO",
        indication: "PHN",
        startedOn: "2026-06-01",
      },
      {
        id: "m-1025-2",
        name: "Atorvastatin",
        dose: "20 mg",
        frequency: "OD",
        route: "PO",
        indication: "Dyslipidemia",
        startedOn: "2024-02-19",
      },
    ],
  }),
  patient({
    id: "p-1026",
    mrn: "MRN-100491",
    firstName: "Fatima",
    lastName: "Zahra",
    dob: "1958-01-19",
    sex: "F",
    phone: "+212 6 78 90 12 34",
    status: "active",
    primaryDiagnosis: "Chemotherapy-induced neuropathy",
    comorbidities: ["Breast cancer (remission)"],
    pharmacist: "Dr. L. Benali",
    department: "Oncology",
    visitType: "Outpatient",
    nextFollowUp: "2026-08-03",
    createdAt: "2026-04-20T10:30:00.000Z",
    medications: [
      {
        id: "m-1026-1",
        name: "Duloxetine",
        dose: "60 mg",
        frequency: "OD",
        route: "PO",
        indication: "CIPN",
        startedOn: "2026-04-20",
      },
      {
        id: "m-1026-2",
        name: "Tramadol",
        dose: "50 mg",
        frequency: "PRN Q6H",
        route: "PO",
        indication: "Breakthrough pain",
        startedOn: "2026-06-11",
      },
    ],
  }),
  patient({
    id: "p-1027",
    mrn: "MRN-100502",
    firstName: "Karim",
    lastName: "Benjelloun",
    dob: "1969-12-05",
    sex: "M",
    phone: "+212 6 40 11 22 33",
    status: "active",
    primaryDiagnosis: "Lumbar radiculopathy",
    comorbidities: ["Obesity"],
    pharmacist: "Dr. S. Cherkaoui",
    department: "Orthopaedics",
    visitType: "Outpatient",
    nextFollowUp: "2026-08-01",
    createdAt: "2026-06-25T14:05:00.000Z",
    medications: [
      {
        id: "m-1027-1",
        name: "Pregabalin",
        dose: "150 mg",
        frequency: "BID",
        route: "PO",
        indication: "Radicular pain",
        startedOn: "2026-06-25",
      },
    ],
  }),
  patient({
    id: "p-1028",
    mrn: "MRN-100515",
    firstName: "Sara",
    lastName: "Idrissi",
    dob: "1985-06-22",
    sex: "F",
    phone: "+212 6 22 33 44 55",
    status: "discharged",
    primaryDiagnosis: "Trigeminal neuralgia",
    comorbidities: [],
    pharmacist: "Dr. L. Benali",
    department: "Neurology",
    visitType: "Outpatient",
    createdAt: "2026-03-14T11:20:00.000Z",
    medications: [
      {
        id: "m-1028-1",
        name: "Carbamazepine",
        dose: "200 mg",
        frequency: "BID",
        route: "PO",
        indication: "Trigeminal neuralgia",
        startedOn: "2026-03-14",
      },
    ],
  }),
  patient({
    id: "p-1029",
    mrn: "MRN-100530",
    firstName: "Omar",
    lastName: "Tazi",
    dob: "1951-03-08",
    sex: "M",
    phone: "+212 6 99 88 77 66",
    status: "active",
    primaryDiagnosis: "Diabetic peripheral neuropathy",
    comorbidities: ["Type 2 Diabetes", "CKD stage 3"],
    pharmacist: "Dr. L. Benali",
    department: "Nephrology",
    visitType: "Inpatient",
    nextFollowUp: "2026-08-04",
    createdAt: "2026-07-01T07:45:00.000Z",
    medications: [
      {
        id: "m-1029-1",
        name: "Gabapentin",
        dose: "300 mg",
        frequency: "TID",
        route: "PO",
        indication: "DPN",
        startedOn: "2026-07-01",
      },
      {
        id: "m-1029-2",
        name: "Insulin glargine",
        dose: "24 U",
        frequency: "OD",
        route: "SC",
        indication: "T2DM",
        startedOn: "2023-11-05",
      },
    ],
  }),
];

function seedAssessment(args: {
  id: string;
  patientId: string;
  date: string;
  createdAt: string;
  responses: DN4Responses;
  recommendation: string;
  notes: string;
  followUp: string;
}): Assessment {
  const p = seedPatients.find((x) => x.id === args.patientId)!;
  return {
    id: args.id,
    patientId: p.id,
    createdAt: args.createdAt,
    updatedAt: args.createdAt,
    assessmentDate: args.date,
    pharmacist: p.pharmacist,
    department: p.department,
    visitType: p.visitType,
    patientSnapshot: {
      mrn: p.mrn,
      fullName: `${p.firstName} ${p.lastName}`,
      age: new Date(args.date).getFullYear() - new Date(p.dob).getFullYear(),
      sex: p.sex,
      primaryDiagnosis: p.primaryDiagnosis,
      comorbidities: [...p.comorbidities],
      allergies: p.allergies,
      medications: p.medications.map((m) => ({ ...m })),
    },
    scales: {
      dn4: {
        scaleId: "dn4",
        version: DN4_VERSION,
        responses: args.responses,
        recordedAt: args.createdAt,
      },
    },
    clinicalContext: {
      chiefComplaint: "Burning pain in both feet, worse at night",
      painLocation: "Bilateral lower limbs",
      painDuration: "6 months",
      painNrs: 6,
    },
    medicationReviews: p.medications.map((m) => ({
      medicationId: m.id,
      name: m.name,
      dose: m.dose,
      frequency: m.frequency,
      route: m.route,
      flags: { effective: true },
      comment: "",
    })),
    recommendation: args.recommendation,
    clinicalNotes: args.notes,
    followUpPlan: args.followUp,
    status: "completed",
  };
}

export const seedAssessments: Assessment[] = [
  seedAssessment({
    id: "as-501",
    patientId: "p-1029",
    date: "2026-07-28",
    createdAt: "2026-07-28T08:15:00.000Z",
    responses: {
      burning: true,
      painfulCold: false,
      electricShock: true,
      tingling: true,
      pricking: true,
      numbness: true,
      itching: false,
      touchHypoesthesia: true,
      prickingHypoesthesia: false,
      brushing: false,
    },
    recommendation: "Continue gabapentin 300 mg TID; renally adjust if eGFR falls below 30 mL/min.",
    notes: "Nocturnal burning pain limiting sleep. Counselled on sedation risk.",
    followUp: "Review in 2 weeks with renal panel.",
  }),
  seedAssessment({
    id: "as-500",
    patientId: "p-1026",
    date: "2026-07-27",
    createdAt: "2026-07-27T09:40:00.000Z",
    responses: {
      burning: true,
      painfulCold: true,
      electricShock: true,
      tingling: true,
      pricking: true,
      numbness: true,
      itching: false,
      touchHypoesthesia: true,
      prickingHypoesthesia: false,
      brushing: false,
    },
    recommendation: "Increase duloxetine to 90 mg OD if tolerated; limit tramadol to PRN use.",
    notes: "Persistent glove-and-stocking distribution following taxane therapy.",
    followUp: "Telephone review in 7 days.",
  }),
  seedAssessment({
    id: "as-499",
    patientId: "p-1025",
    date: "2026-07-25",
    createdAt: "2026-07-25T11:05:00.000Z",
    responses: {
      burning: true,
      painfulCold: false,
      electricShock: true,
      tingling: true,
      pricking: false,
      numbness: true,
      itching: false,
      touchHypoesthesia: true,
      prickingHypoesthesia: false,
      brushing: false,
    },
    recommendation: "Titrate gabapentin to 600 mg TID over 2 weeks.",
    notes: "Post-herpetic distribution T5 dermatome.",
    followUp: "Clinic review in 2 weeks.",
  }),
  seedAssessment({
    id: "as-498",
    patientId: "p-1024",
    date: "2026-07-22",
    createdAt: "2026-07-22T10:00:00.000Z",
    responses: {
      burning: true,
      painfulCold: false,
      electricShock: true,
      tingling: true,
      pricking: true,
      numbness: true,
      itching: false,
      touchHypoesthesia: false,
      prickingHypoesthesia: false,
      brushing: false,
    },
    recommendation: "Titrate pregabalin to 150 mg BID; reinforce glycaemic control.",
    notes: "Symptoms improving on current regimen.",
    followUp: "Review at next diabetes clinic.",
  }),
  seedAssessment({
    id: "as-497",
    patientId: "p-1027",
    date: "2026-07-18",
    createdAt: "2026-07-18T13:30:00.000Z",
    responses: {
      burning: false,
      painfulCold: false,
      electricShock: true,
      tingling: true,
      pricking: true,
      numbness: true,
      itching: false,
      touchHypoesthesia: false,
      prickingHypoesthesia: false,
      brushing: false,
    },
    recommendation: "Continue pregabalin 150 mg BID; add physiotherapy referral.",
    notes: "L5 radicular distribution, no red flags.",
    followUp: "Review in 4 weeks.",
  }),
];

export const seedSnapshot: ClinicalSnapshot = {
  patients: seedPatients,
  assessments: seedAssessments,
};
